server:
    port: 9000
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/wepay?useSSL=false
        username: root
        password: XXXXXX
    jpa:
        generate-ddl: true
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
